# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Timezone Configuration
timezone: Asia/Kolkata

# jekyll-seo-tag settings
title: Vidhi Lodha
tagline: A Journey in Physiotherapy and Beyond
description: >-
  A personal blog by Vidhi Lodha—sharing insights on physiotherapy, experiences, and personal growth.

# Fill in the protocol & hostname for your site.
url: "https://vidhilodha315.github.io"

github:
  username: vidhilodha315 # Updated GitHub username

twitter:
  username: "" # Add Twitter username if available

social:
  name: Vidhi Lodha
  email: vidhilodha.me315@gmail.com
  links:
    - https://github.com/vidhilodha315
    # Uncomment and add other links if available
    # - https://www.linkedin.com/in/vidhi-lodha
    # - https://twitter.com/vidhilodha

# Site Verification Settings
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
  facebook: 

# Web Analytics Settings
analytics:
  google:
    id: ""  # Fill in your Google Analytics ID if needed

# Page views settings
pageviews:
  provider: ""

# Theme mode (light/dark)
theme_mode: light  # Default to light mode

# The CDN endpoint for media resources
cdn: ""

# Sidebar avatar (change if needed)
avatar: "./assets/img/avatar.png"

# Social preview image
social_preview_image: ""

# Table of Contents (TOC) global setting
toc: true

comments:
  provider: "" # Enable if using Disqus, Utterances, or Giscus

# Self-hosted static assets (optional)
assets:
  self_host:
    enabled: false

pwa:
  enabled: false  # PWA (Installable feature)
  cache:
    enabled: true
    deny_paths: []

paginate: 10

# Base URL (Keep empty for GitHub Pages)
baseurl: ""

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# The favicon settings
favicon:
  path: /static/favicons/

exclude:
  - assets/img/favicons/site.webmanifest
  - _static/favicons/site.webmanifest
